title: BREAKTEXT
description: "A blog covering typography and highlighting its use and importance
  in the modern world. "
header_text: "Breaking the complexity of typographic design. "
footer_text: Copyright 2020 Seb Ingham
header_feature_image: ../uploads/sat.jpg
bannerheight: 100vh
logo: ../uploads/btfavicon.png
favicon: ../uploads/btfavicon.png
gridlayout: true
fixednavbar: true
upzoom: true
