title: BREAKTEXT
description: "A blog covering typography and highlighting its use and importance
  in the modern world. "
header_text: Differing types of letters from differing types of life.
footer_text: Copyright 2020 Seb Ingham
header_feature_image: ../uploads/hsjoe-yates-cc4stor2oc0-unsplash.png
bannerheight: 40vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
