title: BREAKTEXT
description: "A blog covering typography and highlighting its use and importance
  in the modern world. "
header_text: "Breaking the complexity of typographic design. "
footer_text: Copyright 2020 Seb Ingham
header_feature_image: ../uploads/cristagupa.jpg
bannerheight: 20vmax
logo: ../uploads/btv23000.png
favicon: ../uploads/btv23000.png
gridlayout: false
fixednavbar: true
upzoom: true
