title: Breaking the complexity of typographic design.
description: "A blog covering typography and highlighting its use and importance
  in the modern world. "
header_text: Differing types of letters from differing types of life.
footer_text: Copyright 2020 Seb Ingham
header_feature_image: ../uploads/sam_roman.jpg
bannerheight: 20vmax
logo: ../uploads/breaktextlogosgreen-xxx-.png
favicon: ../uploads/breaktextlogosgreen-xxx-.png
gridlayout: false
fixednavbar: true
upzoom: true
